changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking changes
      labels:
        - breaking
        - security
    - title: Additions
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation and distribution
      labels:
        - documentation
        - release
        - packaging
    - title: Other changes
      labels:
        - "*"
